# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.cache/wt [current_project]
set_property parent.project_path C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/FFD_CLOCK_ENABLE.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/new/TX_control.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/new/TX_sequence.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/new/UART_RX_CTRL.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/new/UART_tx_control_wrapper.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/alu.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/imports/display_BCD/bcd_to_sevenseg_hex.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/imports/cosas/clockmaster.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/imports/display_BCD/counter_3bit.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/new/disp_driver.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/imports/display_BCD/display_bcd.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/imports/display_BCD/display_multiplexer_4bits.sv
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/new/top_module.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/uart/data_sync.v
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/uart/uart_basic.v
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/uart/uart_baud_tick_gen.v
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/uart/uart_rx.v
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/uart/uart_tx.v
  C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/double-dabble-32bits/unsigned_to_bcd.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files C:/Users/mewf1/Documents/Vivado/lab_2/exp_7_4_uartmala/exp_7_4_uartmala.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc]


synth_design -top top_module -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
